const content = {
  uz: {
    home: "Uy",
    explore: "O'rganing",
    notification: "Bildirishnoma",
    messages: "Xabarlar",
    bookmarks: "Xatcho'plar",
    lists: "Ro'yxatlar",
    profile: "Profil",
    more: "Ko'proq",
    searchPlaceholder: "Nimalar bo'lyapti",
    searchTweet: "Twitter qidirish",
    trend: "Siz uchun trendlar",
    trending: "Germaniyada trend",
    revolution: "Qayta baholash",
    likeYou: "Sizga yoqishi mumkin",
    follow: "Kuzatish",
    terms: "Xizmat ko'rsatish shartlari",
    policy: "Maxfiylik siyosati",
    cookiePolicy: "Cookie siyosati",
    imprint: "Bosib chiqarish",
    adsInfo: "Reklama haqida ma'lumot",
    menuMore: "Ko'proq ···",
    coopywrite: "© 2021 Twitter, Inc.",
    trendsMore: "Ko'proq ko'rsatish",
    heppening: "Nimalar bo'lyapti",
    search: "Twitter qidirish",
  },
  ru: {
    home: "Дом",
    explore: "Исследовать",
    notification: "Уведомления",
    messages: "Сообщения",
    bookmarks: "Закладки",
    lists: "Списки",
    profile: "Профиль",
    more: "Более",
    searchPlaceholder: "Что творится",
    searchTweet: "Искать в Twitter",
    trend: "Тенденции для вас",
    trending: "тренд в Германии",
    revolution: "Переоценка",
    likeYou: "Вам может понравиться",
    follow: "Отслеживание",
    terms: "Условия обслуживания",
    policy: "Политика конфиденциальности",
    cookiePolicy: "Политика использования файлов cookie",
    imprint: "Отпечаток",
    adsInfo: "Информация о рекламе",
    menuMore: "Более ···",
    coopywrite: "© Twitter, Inc., 2021 г.",
    trendsMore: "Показать еще",
    heppening: "Что творится",
    search: "Искать в Twitter",
  },
  en: {
    home: "Home",
    explore: "Explore",
    notification: "Notification",
    messages: "Messages",
    bookmarks: "Bookmarks",
    lists: "Lists",
    profile: "Profile",
    more: "More",
    searchPlaceholder: "What’s happening",
    searchTweet: "Search Twitter",
    trend: "Trends for you",
    trending: "Trending in Germany",
    revolution: "Revolution",
    likeYou: "You might like",
    follow: "Follow",
    paragraf: "Terms of Service Privacy Policy Cookie Policy",
    paragraf2: "Imprint Ads Info More ··· © 2021 Twitter, Inc.",
    trendsMore: "Show more",
    heppening: "What’s happening",
    search: "Search Twitter",
    terms: "Terms of Service",
    policy: "Privacy Policy",
    cookiePolicy: "Cookie Policy",
    imprint: "Imprint",
    adsInfo: "Ads Info",
    menuMore: "More ···",
    coopywrite: "© 2021 Twitter, Inc.",
  },
};

export default content;
